name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: trpo2023/cw-iv-221_game_tag
      with:
        cmake-version: '3.21'

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
    
    - name: Run tests
      run: |
        cd build
        ctest -VV
